export const navItems = [
  { label: "خانه", href: "/" },
  { label: "اوستا", href: "/avesta" },
  { label: "زرتشت", href: "/zoroaster" },
  { label: "فروشگاه", href: "/shop" },
  { label: "کتابخانه", href: "/library" },
];

export const exploreNavItems = [
  { label: "دین زرتشتی", href: "/zoroastrianism", description: "باور، آیین و میراث زنده" },
  { label: "واژه‌نامه", href: "/dictionary", description: "مفهوم‌ها و ریشه‌های اوستایی" },
  { label: "مقاله‌ها", href: "/articles", description: "خوانش پژوهشی و امروزی" },
  { label: "رسانه", href: "/media", description: "تصویر، صدا و روایت" },
  { label: "موبد هوشمند", href: "/mobed", description: "پرسش منبع‌دار و مسیر مطالعه" },
  { label: "نمایشگاه‌ها", href: "/exhibitions", description: "موزه دیجیتال ایران باستان" },
  { label: "تایم‌لاین", href: "/timeline", description: "مسیر تاریخ و فرهنگ" },
  { label: "روش پژوهش", href: "/research-methodology", description: "منابع و شیوه خوانش" },
  { label: "فروشگاه", href: "/shop", description: "محصولات فرهنگی" },
];

export const routeMap = [
  "/",
  "/fa",
  "/en",
  "/onboarding",
  "/avesta",
  "/avesta/yasna",
  "/avesta/gathas",
  "/avesta/visperad",
  "/avesta/visperad/visperad-starter",
  "/avesta/vendidad",
  "/avesta/vendidad/fargard-1",
  "/avesta/vendidad/fargard-2",
  "/avesta/yashts",
  "/avesta/yashts/aban-yasht",
  "/avesta/yashts/mehr-yasht",
  "/avesta/khordeh-avesta",
  "/avesta/khordeh-avesta/daily-prayers",
  "/avesta/khordeh-avesta/atash-niyayesh",
  "/avesta/hats",
  "/avesta/hats/ha-map",
  "/world",
  "/tour",
  "/exhibitions",
  "/dashboard",
  "/daily-light",
  "/wisdom-capsule",
  "/compass",
  "/privacy-center",
  "/research-methodology",
  "/contact",
  "/zoroaster",
  "/gathas",
  "/zoroastrianism",
  "/monotheism",
  "/monotheism/paths",
  "/newsletter",
  "/newsletter/archive",
  "/newsletter/html-export",
  "/newsletter/preferences",
  "/newsletter/preview",
  "/cyrus",
  "/citations",
  "/calendar",
  "/campaigns",
  "/achievements",
  "/streak",
  "/collections",
  "/concept-map",
  "/dictionary",
  "/journey-builder",
  "/ai-studio",
  "/mobed",
  "/quests",
  "/reflection",
  "/practice",
  "/asha-balance",
  "/share-studio",
  "/ritual-room",
  "/search",
  "/reading-room",
  "/trust-center",
  "/wisdom-guide",
  "/study-plan",
  "/timeline",
  "/shop",
  "/shop/checkout",
  "/shop/payment/demo",
  "/admin",
  "/admin/go-live",
  "/admin/deployment-readiness",
  "/admin/page-quality",
  "/admin/global-growth-audit",
  "/admin/localization",
  "/admin/route-visibility",
  "/admin/product-analytics",
  "/admin/event-tracking",
  "/admin/event-collector",
  "/admin/team-handoff",
  "/admin/exhibitions",
  "/admin/inventory",
  "/admin/production",
  "/admin/production/briefs",
  "/admin/production/review",
  "/admin/visual-assets",
  "/admin/source-registry",
  "/admin/source-intake",
  "/admin/citation-coverage",
  "/admin/source-review",
  "/admin/avesta",
  "/admin/avesta-completion",
  "/admin/avesta-production",
  "/admin/avesta-publication-gates",
  "/admin/avesta-release-waves",
  "/admin/avesta-feature-flags",
  "/admin/avesta-access-control",
  "/admin/avesta-source-packs",
  "/admin/avesta-import-template",
  "/admin/articles",
  "/admin/calendar",
  "/admin/editorial",
  "/admin/glossary",
  "/admin/library",
  "/admin/media",
  "/admin/newsletter",
  "/admin/newsletter/analytics",
  "/admin/newsletter/experiments",
  "/admin/newsletter/send-times",
  "/admin/newsletter/schedule",
  "/admin/newsletter/delivery",
  "/admin/shop",
  "/admin/import",
  "/admin/seo",
  "/library",
  "/library/archive",
  "/memory",
  "/media",
  "/articles",
  "/login",
  "/register",
  "/profile",
  "/about"
];

export const introCards = [
  {
    title: "اوستا چیست؟",
    description: "دروازه‌ای به متن‌های بنیادین، نیایش‌ها، حکمت و جهان‌بینی ایران باستان.",
    href: "/avesta",
    atmosphere: "scene-fire"
  },
  {
    title: "زرتشت کیست؟",
    description: "پیام‌آور خرد، راستی و انتخاب آگاهانه میان روشنایی و تاریکی.",
    href: "/zoroaster",
    atmosphere: "scene-prophet"
  },
  {
    title: "گات‌ها چیست؟",
    description: "کهن‌ترین سروده‌های منسوب به زرتشت؛ متن‌هایی برای اندیشه، اخلاق و معنا.",
    href: "/gathas",
    atmosphere: "scene-sunrise"
  },
  {
    title: "اهورامزدا",
    description: "نماد دانایی، روشنایی و نظم اخلاقی در قلب آموزه‌های زرتشتی.",
    href: "/zoroastrianism",
    atmosphere: "scene-cosmic"
  }
];

export const avestaSections = [
  {
    title: "یسنا",
    slug: "yasna",
    href: "/avesta/yasna",
    description: "نیایش‌ها، هوم‌ها و آیین‌های بنیادین؛ جایی که آتش، سرود و روشنایی به هم می‌رسند.",
    atmosphere: "scene-fire",
    coverImage: "/images/ai/yasna-hero.jpg",
    roman: "I"
  },
  {
    title: "گات‌ها",
    slug: "gathas",
    href: "/avesta/gathas",
    description: "سرودهای ژرف و روشن زرتشت؛ آرام، الهی و سرشار از معنا.",
    atmosphere: "scene-sunrise",
    coverImage: "/images/ai/gathas-hero.jpg",
    roman: "II"
  },
  {
    title: "ویسپرد",
    slug: "visperad",
    href: "/avesta/visperad",
    description: "متن آیینی برای تکمیل نیایش‌ها و بزرگداشت همه ردان و نیروهای نیک.",
    atmosphere: "scene-tablets",
    coverImage: "/images/ai/avesta-portal.jpg",
    roman: "III"
  },
  {
    title: "وندیداد",
    slug: "vendidad",
    href: "/avesta/vendidad",
    description: "قانون، پاکی و رازهای تاریک‌تر اوستا در فضایی پرهیبت و رمزآلود.",
    atmosphere: "scene-stone",
    coverImage: "/images/ai/vendidad-hero.jpg",
    roman: "IV"
  },
  {
    title: "یشت‌ها",
    slug: "yashts",
    href: "/avesta/yashts",
    description: "سرودهای حماسی برای ایزدان، طبیعت، آسمان، آب، مهر و پیروزی.",
    atmosphere: "scene-mountain",
    coverImage: "/images/ai/yashts-hero.jpg",
    roman: "V"
  },
  {
    title: "خرده اوستا",
    slug: "khordeh-avesta",
    href: "/avesta/khordeh-avesta",
    description: "نیایش‌های روزانه، آرامش شخصی و حضور روشنایی در زندگی معمول.",
    atmosphere: "scene-scroll",
    coverImage: "/images/ai/khordeh-avesta-hero.jpg",
    roman: "VI"
  },
  {
    title: "هات‌ها",
    slug: "hats",
    href: "/avesta/hats",
    description: "نقشه مطالعه، طومار فصل‌ها و مسیر ورود به متن‌های جزءبه‌جزء.",
    atmosphere: "scene-portrait",
    coverImage: "/images/ai/hats-hero.jpg",
    roman: "VII"
  }
];

export const featuredArticles = [
  "اشا؛ نظم راستی در جهان زرتشتی",
  "فروهر در هنر و اندیشه ایران باستان",
  "گات‌ها و پیام اخلاقی برای انسان امروز"
];
