export type LaunchReadinessStatus = "ready" | "warning" | "blocked";

export type LaunchReadinessItem = {
  id: string;
  label: string;
  area: string;
  status: LaunchReadinessStatus;
  score: number;
  evidence: string;
  nextAction: string;
};

export const launchReadinessItems: LaunchReadinessItem[] = [
  {
    id: "routes",
    label: "مسیرها و معماری سایت",
    area: "Frontend",
    status: "ready",
    score: 92,
    evidence: "صفحات اصلی، پورتال اوستا، مقاله، رسانه، کتابخانه، جستجو، پروفایل و ادمین ساخته شده‌اند.",
    nextAction: "پس از نصب npm، build کامل Next و تست responsive گرفته شود.",
  },
  {
    id: "seo",
    label: "SEO و metadata",
    area: "SEO",
    status: "ready",
    score: 88,
    evidence: "metadata داینامیک، sitemap، robots، manifest و schema های اصلی آماده‌اند.",
    nextAction: "پس از ورود محتوای واقعی، title و description هر صفحه بازبینی شود.",
  },
  {
    id: "content",
    label: "محتوای اوستا و مقاله‌ها",
    area: "Content",
    status: "warning",
    score: 54,
    evidence: "ساختار متن، ترجمه، بازنویسی، تحلیل، پیام اخلاقی و import آماده است؛ متن نهایی هنوز کامل نیست.",
    nextAction: "متن‌های نهایی اوستا، ترجمه‌ها و منابع پژوهشی از پنل ادمین یا bulk import وارد شوند.",
  },
  {
    id: "media",
    label: "تصویر، صوت و دارایی‌ها",
    area: "Media",
    status: "warning",
    score: 48,
    evidence: "پلیر صوتی، رسانه، upload و prompt library آماده است؛ فایل‌های نهایی تصویر و صوت هنوز باید بارگذاری شوند.",
    nextAction: "تصاویر AI، فایل‌های صوتی و thumbnail های نهایی در public یا storage قرار بگیرند.",
  },
  {
    id: "database",
    label: "دیتابیس و Prisma",
    area: "Backend",
    status: "warning",
    score: 62,
    evidence: "schema، seed، repository fallback و API های اصلی آماده‌اند؛ DATABASE_URL تولیدی هنوز تنظیم نشده است.",
    nextAction: "PostgreSQL production، migrate و seed اجرا شود.",
  },
  {
    id: "admin-security",
    label: "امنیت ادمین و نقش‌ها",
    area: "Security",
    status: "warning",
    score: 68,
    evidence: "ماتریس نقش‌ها، تشخیص نقش demo، middleware ادمین، گارد دسترسی اوستا و guard داخلی APIها اضافه شده‌اند.",
    nextAction: "برای production، session امن، hash رمز، User.role دیتابیس و تست نفوذ مسیرهای ادمین اضافه شود.",
  },
  {
    id: "audit",
    label: "Audit Log و کنترل تغییرات",
    area: "Governance",
    status: "warning",
    score: 74,
    evidence: "بورد audit، API، مدل Prisma و ثبت رخداد برای ذخیره محتوا، آپلود رسانه و import اضافه شده‌اند.",
    nextAction: "پس از اجرای migrate، رخدادهای auth، تغییر نقش‌ها و عملیات SEO هم به audit persistent وصل شوند.",
  },
  {
    id: "deploy",
    label: "Deploy و محیط اجرا",
    area: "DevOps",
    status: "blocked",
    score: 35,
    evidence: "راهنمای deploy و فایل‌های پروژه آماده‌اند؛ build کامل به npm و نصب وابستگی‌ها نیاز دارد.",
    nextAction: "npm install، prisma generate و next build در محیط تیم فنی اجرا شود.",
  },
  {
    id: "commerce",
    label: "فروشگاه فرهنگی",
    area: "Commerce",
    status: "warning",
    score: 86,
    evidence: "صفحه فروشگاه، صفحه محصول، checkout demo، کد تخفیف، مالیات، روش ارسال، API سفارش/پرداخت/موجودی/گزارش، پنل محصول/انبار/سفارش/پرداخت/فروش و مدل‌های Commerce آماده شده‌اند.",
    nextAction: "درگاه واقعی، webhook امن، اتصال انبار/شرکت ارسال، خروجی مالیاتی و گزارش فروش بازه‌ای قبل از فروش واقعی اضافه شود.",
  },
  {
    id: "wisdom-guide",
    label: "راهنمای خرد و شخصی‌سازی مطالعه",
    area: "Experience",
    status: "ready",
    score: 80,
    evidence: "صفحه راهنمای خرد، پنل انتخاب حال‌وهوا، API پیشنهاد، اتصال به بند اوستا، واژه‌نامه، مقاله و مسیرهای بعدی ساخته شده است.",
    nextAction: "در فاز AI، راهنما به RAG، Meilisearch، پروفایل کاربر و گاردریل تحریریه وصل شود.",
  },
  {
    id: "journey-builder",
    label: "سازنده مسیر شخصی",
    area: "Experience",
    status: "ready",
    score: 84,
    evidence: "صفحه Journey Builder، API، انتخاب نیت/ریتم/سطح/سبک تجربه و تولید مسیر مطالعه/نیایش/رسانه/کردار اضافه شده‌اند.",
    nextAction: "در فاز پروفایل و AI، مسیرها به تاریخچه مطالعه، bookmark، RAG و event analytics وصل شوند.",
  },
  {
    id: "share-studio",
    label: "استودیوی نقل‌قول طلایی",
    area: "Growth",
    status: "ready",
    score: 83,
    evidence: "صفحه Share Studio، API، انتخاب نقل‌قول، تم، فرمت، کپی متن، دانلود SVG و CTA برگشت به منبع اضافه شده‌اند.",
    nextAction: "در فاز production، خروجی PNG سروری، social scheduler، templateهای برند و analytics share اضافه شود.",
  },
  {
    id: "ritual-room",
    label: "تالار آیینی زنده",
    area: "Experience",
    status: "ready",
    score: 84,
    evidence: "صفحه Ritual Room، API، حالت‌های آتش/نفس/مطالعه/سپاس، تایمر، مراحل آیینی و اتصال به Reflection/Share Studio اضافه شده‌اند.",
    nextAction: "در فاز اپ موبایل، streak، صوت راهنما، یادآور، haptic و تاریخچه ritual به پروفایل وصل شود.",
  },
  {
    id: "ai-art-studio",
    label: "استودیوی تصویرسازی AI",
    area: "Media",
    status: "ready",
    score: 82,
    evidence: "صفحه استودیوی AI، API briefها، اتصال به پنل رسانه، پرامپت، negative prompt، پالت، نسبت تصویر و چک‌لیست تولید آماده است.",
    nextAction: "در فاز بعد، صف تولید تصویر، storage، تایید تحریریه و اتصال مستقیم خروجی به MediaAsset اضافه شود.",
  },
  {
    id: "trust-center",
    label: "مرکز اعتماد و منابع",
    area: "Governance",
    status: "ready",
    score: 84,
    evidence: "صفحه Trust Center، API، رکوردهای اعتماد، سطح اطمینان، وضعیت منبع، بازبینی و قدم بعدی پژوهشی به سایت اضافه شده است.",
    nextAction: "در فاز CMS، citation واقعی، نسخه منابع، تایید ویراستار، تاریخچه تغییرات و DOI/metadata کتابخانه‌ای اضافه شود.",
  },
  {
    id: "citations",
    label: "Citation و ارجاع پژوهشی",
    area: "Content Governance",
    status: "ready",
    score: 81,
    evidence: "مرکز ارجاع، API Citation، رکوردهای منبع، وضعیت تایید/بازبینی، اتصال به کتابخانه و سرچ اضافه شده‌اند.",
    nextAction: "در فاز دیتابیس، مدل Citation، پانویس صفحه‌ای، شماره صفحه، نسخه منبع و workflow تایید پژوهشی اضافه شود.",
  },
  {
    id: "editorial-command",
    label: "مرکز فرماندهی تحریریه",
    area: "Editorial Ops",
    status: "ready",
    score: 83,
    evidence: "صفحه مستقل گردش‌کار تحریریه، API ارتقایافته، deadline، blocker، checklist، مالک، بازبین و هدف انتشار اضافه شده‌اند.",
    nextAction: "در فاز CMS، assignment واقعی، تغییر status، کامنت داخلی و اعلان برای deadlineها اضافه شود.",
  },
  {
    id: "publishing-calendar",
    label: "تقویم انتشار و کمپین محتوا",
    area: "Editorial Ops",
    status: "ready",
    score: 82,
    evidence: "صفحه تقویم انتشار، API ادمین، کمپین‌ها، channelها، deliverableها، اتصال به تسک‌های تحریریه و readiness اضافه شده‌اند.",
    nextAction: "در فاز بعد، scheduled publishing، اعلان deadline، تقویم شبکه اجتماعی و launch calendar فروشگاه اضافه شود.",
  },
  {
    id: "reading-room",
    label: "تالار مطالعه زنده",
    area: "Reader Experience",
    status: "ready",
    score: 84,
    evidence: "صفحه Reading Room، API، حالت‌های مطالعه، عمق توضیح، پیشنهاد واژه‌نامه، مسیر بعدی و اتصال به صفحه خانه/جستجو اضافه شده‌اند.",
    nextAction: "در فاز پروفایل، پیشرفت صوتی، یادداشت‌ها، بوکمارک‌ها و پیشنهادهای AI به حساب کاربر متصل شوند.",
  },
  {
    id: "concept-map",
    label: "نقشه مفهومی اوستا",
    area: "Discovery",
    status: "ready",
    score: 82,
    evidence: "صفحه Concept Map، API، گره‌ها، پیوندها، فیلتر نوع محتوا، جستجو و اتصال به خانه/جستجو/sitemap اضافه شده‌اند.",
    nextAction: "در فاز CMS، ارتباطات معنایی توسط ادمین ساخته شوند و پیشنهادهای AI بعد از تایید تحریریه وارد نقشه شوند.",
  },
  {
    id: "world-map",
    label: "نقشه جهان دیجیتال",
    area: "Product Experience",
    status: "ready",
    score: 86,
    evidence: "صفحه World، API نقشه جهان، قلمروهای محصول، درصد تکامل، قفل‌های بعدی، اتصال به خانه/ناوبری/جستجو/sitemap اضافه شده‌اند.",
    nextAction: "در فاز analytics، تکامل هر قلمرو از داده واقعی محتوا، رفتار کاربر، فروشگاه و readiness محاسبه شود.",
  },
  {
    id: "team-handoff",
    label: "کنسول تحویل تیم‌ها",
    area: "Product Ops",
    status: "ready",
    score: 84,
    evidence: "صفحه Admin Team Handoff، API تیم‌ها، سند مادر تحویل، مسیرهای کلیدی، سندهای لازم و خروجی‌های هر تیم اضافه شده‌اند.",
    nextAction: "در فاز مدیریت پروژه، خروجی‌های هر تیم به ابزار issue tracker، owner واقعی و deadline متصل شوند.",
  },
  {
    id: "go-live-command",
    label: "Go-Live Command Center",
    area: "Product Ops",
    status: "ready",
    score: 83,
    evidence: "صفحه Admin Go-Live، API go-live، gateهای pass/watch/stop، launch mode، مالک هر gate و دستور اقدام قبل از بالا آوردن دامنه اضافه شده‌اند.",
    nextAction: "در فاز CI/CD، این gateها به build status، DNS، env production، uptime و deployment provider وصل شوند.",
  },
  {
    id: "page-quality-matrix",
    label: "ماتریس کنترل کیفیت صفحات",
    area: "QA",
    status: "ready",
    score: 82,
    evidence: "صفحه Admin Page Quality، API کیفیت صفحات، امتیاز routeها، ریسک، مالک، checklist و اقدام بعدی برای QA قبل از لانچ اضافه شده‌اند.",
    nextAction: "در فاز QA، این ماتریس به Playwright، Lighthouse، visual regression، analytics و completeness واقعی CMS وصل شود.",
  },
  {
    id: "product-analytics",
    label: "آنالیتیکس محصول و قیف تجربه",
    area: "Growth",
    status: "ready",
    score: 80,
    evidence: "صفحه Admin Product Analytics، API، قیف ورود/اوستا/جستجو/خبرنامه/فروشگاه و event specهای production اضافه شده‌اند.",
    nextAction: "در فاز production، eventها به PostHog/Matomo/GA4 یا جدول first-party events و UTM attribution وصل شوند.",
  },
  {
    id: "event-tracking-matrix",
    label: "ماتریس Event Tracking",
    area: "Growth",
    status: "ready",
    score: 81,
    evidence: "صفحه Admin Event Tracking، API، payload contract، مقصد ابزارها، QA rule، privacy note و checklist اتصال production اضافه شده‌اند.",
    nextAction: "تیم فنی helper مشترک track، endpoint first-party events و اتصال PostHog/GA4 را پیاده‌سازی کند.",
  },
  {
    id: "first-party-event-collector",
    label: "کلکتور رویدادهای داخلی",
    area: "Growth",
    status: "ready",
    score: 82,
    evidence: "API عمومی /api/events، helper سمت کلاینت، validation، sanitize، memory preview، صفحه Admin Event Collector و instrument شدن CTAهای خانه/اوستا اضافه شده‌اند.",
    nextAction: "در production، رویدادهای پذیرفته‌شده به Prisma Event table، warehouse و fan-out consent-aware وصل شوند و باقی CTAها instrument شوند.",
  },
  {
    id: "privacy-consent-center",
    label: "مرکز حریم خصوصی و رضایت کاربر",
    area: "Trust",
    status: "ready",
    score: 87,
    evidence: "صفحه Privacy Center، بنر جهانی رضایت، API consent، policy دسته‌های داده، تنظیمات local consent و اتصال consent-aware به trackEvent اضافه شده‌اند.",
    nextAction: "در production، consent history به دیتابیس، policy versioning، geo/legal copy و audit قانونی/حریم خصوصی وصل شود.",
  },
  {
    id: "content-inventory",
    label: "Inventory تکمیل محتوا",
    area: "Product Ops",
    status: "ready",
    score: 78,
    evidence: "صفحه Admin Inventory، API inventory، شمارش متن/تصویر/صوت/منبع/ادمین برای هر قلمرو و اتصال به سایدبار/routeMap اضافه شده‌اند.",
    nextAction: "در فاز CMS، اعداد inventory از دیتابیس واقعی، storage رسانه و وضعیت citation محاسبه شوند.",
  },
  {
    id: "production-queue",
    label: "صف تولید محتوا و دارایی",
    area: "Product Ops",
    status: "ready",
    score: 79,
    evidence: "صفحه Admin Production، API production queue، تبدیل کمبودهای Inventory به تسک متن/تصویر/صوت/منبع/ادمین و اتصال به سایدبار/routeMap اضافه شده‌اند.",
    nextAction: "در فاز CMS، تسک‌ها به assignment واقعی، وضعیت تولید، فایل‌های DAM و اعلان deadline وصل شوند.",
  },
  {
    id: "production-briefs",
    label: "Brief Studio تولید",
    area: "Product Ops",
    status: "ready",
    score: 80,
    evidence: "صفحه Admin Production Briefs، API briefها، هدف تولید، فرمت خروجی، معیار پذیرش و prompt تصویر AI برای تسک‌های صف تولید اضافه شده‌اند.",
    nextAction: "در فاز DAM/CMS، briefها به assignment واقعی، خروجی فایل، review و history تولید وصل شوند.",
  },
  {
    id: "production-review",
    label: "Review Gate تولید",
    area: "Product Ops",
    status: "ready",
    score: 81,
    evidence: "صفحه Admin Production Review، API review، وضعیت تایید/اصلاح/blocker، امتیاز کیفیت، ایرادها و تصمیم انتشار برای خروجی‌های brief اضافه شده‌اند.",
    nextAction: "در فاز CMS/DAM، reviewها به قفل انتشار، کامنت بازبین، نسخه فایل و تاریخچه approval وصل شوند.",
  },
  {
    id: "learning-quests",
    label: "مأموریت‌های خرد و XP",
    area: "Engagement",
    status: "ready",
    score: 83,
    evidence: "صفحه Quests، API، XP، badge، سطح کاربر، مأموریت‌ها، ذخیره محلی پیشرفت و اتصال به خانه/جستجو/sitemap اضافه شده‌اند.",
    nextAction: "در فاز حساب کاربری، XP و badgeها در دیتابیس ذخیره شوند و مأموریت‌های شخصی‌سازی‌شده تولید شوند.",
  },
  {
    id: "achievement-hall",
    label: "تالار نشان‌ها و وفادارسازی",
    area: "Engagement",
    status: "ready",
    score: 82,
    evidence: "صفحه Achievements، API، snapshot نشان‌ها، سطح کاربر، پیشرفت، badgeهای فعال و کنترل local progress اضافه شده‌اند.",
    nextAction: "در فاز پروفایل، achievementها به user events، streak، quest completion و sync بین دستگاه‌ها وصل شوند.",
  },
  {
    id: "daily-streak",
    label: "زنجیره روشنایی و عادت روزانه",
    area: "Engagement",
    status: "ready",
    score: 80,
    evidence: "صفحه Streak، API، تقویم ۱۴ روزه، اتصال local به دفتر روزانه و مأموریت‌ها و CTAهای برگشت کاربر اضافه شده‌اند.",
    nextAction: "در production، streak events، push reminder، email reminder و sync چنددستگاهی به پروفایل وصل شود.",
  },
  {
    id: "personal-dashboard",
    label: "نورخانه شخصی و مرکز ورود روزانه",
    area: "Retention",
    status: "ready",
    score: 84,
    evidence: "صفحه Dashboard، API، جمع‌بندی daily avesta، streak، quest، achievement، last read، پیشنهادهای روزانه و مسیرهای سریع اضافه شده‌اند.",
    nextAction: "در production، snapshot از event stream و پروفایل واقعی ساخته شود و recommendation engine شخصی‌سازی شود.",
  },
  {
    id: "wisdom-compass",
    label: "قطب‌نمای خرد و پیشنهاد قدم بعدی",
    area: "Retention",
    status: "ready",
    score: 83,
    evidence: "صفحه Compass، API، سیگنال‌های مطالعه/تأمل/مأموریت/پژوهش و پیشنهاد next-best-action اضافه شده‌اند.",
    nextAction: "در production، امتیازدهی rule-based به event stream، Meilisearch signals، RAG و گاردریل تحریریه وصل شود.",
  },
  {
    id: "reader-memory",
    label: "حافظه مطالعه و مسیر شخصی",
    area: "Retention",
    status: "ready",
    score: 85,
    evidence: "صفحه Memory، API manifest، اتصال به پروفایل، XP/quest، بوکمارک، یادداشت، برنامه مطالعه و route/search/home اضافه شده‌اند.",
    nextAction: "در فاز پروفایل واقعی، حافظه از localStorage به مدل‌های دیتابیس و sync بین دستگاه‌ها منتقل شود.",
  },
  {
    id: "daily-reflection",
    label: "دفتر پندار، گفتار، کردار",
    area: "Retention",
    status: "ready",
    score: 84,
    evidence: "صفحه Reflection، API، ذخیره محلی روزانه، سه ستون اخلاقی و اتصال به اوستای امروز/حافظه/مأموریت‌ها اضافه شده‌اند.",
    nextAction: "در فاز حساب کاربری، ثبت‌های روزانه به دیتابیس، یادآور، streak و گزارش رشد اخلاقی وصل شوند.",
  },
  {
    id: "sacred-calendar",
    label: "گاه‌شمار آیینی و فرهنگی",
    area: "Content Experience",
    status: "ready",
    score: 82,
    evidence: "صفحه Calendar، صفحه اختصاصی هر مناسبت، API عمومی/جزئی، رویدادهای نوروز/تیرگان/مهرگان/سده، مسیر مطالعه، ایده تجربه و ایده محصول فرهنگی اضافه شده‌اند.",
    nextAction: "در فاز CMS، رویدادها به مدل دیتابیس، اعلان‌ها، landing campaign، مقاله‌های فصلی و کالکشن فروشگاه وصل شوند.",
  },
  {
    id: "seasonal-campaign-studio",
    label: "استودیوی کمپین فصلی",
    area: "Growth",
    status: "ready",
    score: 81,
    evidence: "صفحه Campaigns، API، بسته کمپین برای هر مناسبت، کانال‌های خانه/مقاله/رسانه/ایمیل/فروشگاه، asset و چک‌لیست لانچ اضافه شده‌اند.",
    nextAction: "در فاز بعد، کمپین‌ها به scheduled banners، email provider، کالکشن واقعی فروشگاه و تقویم انتشار ادمین وصل شوند.",
  },
  {
    id: "newsletter-digest",
    label: "خبرنامه روشنایی",
    area: "Growth",
    status: "ready",
    score: 80,
    evidence: "صفحه Newsletter، تنظیمات و لغو عضویت، آرشیو نورنامه، پیش‌نمایش قالب ایمیل، خروجی HTML ایمیل، پنل ادمین خبرنامه، آنالیتیکس خبرنامه، A/B Lab، بهینه‌ساز زمان ارسال، صف انتشار نورنامه، مانیتور تحویل نورنامه، API عمومی/ادمین، فرم واقعی عضویت، انتخاب موضوع، ذخیره محلی، اتصال به خانه و جستجو اضافه شده‌اند.",
    nextAction: "در فاز production، double opt-in، email provider، segment کاربر، unsubscribe و گزارش نرخ تبدیل اضافه شود.",
  },
];

export function getLaunchReadinessSummary(items: LaunchReadinessItem[] = launchReadinessItems) {
  const averageScore = Math.round(items.reduce((sum, item) => sum + item.score, 0) / items.length);
  const ready = items.filter((item) => item.status === "ready").length;
  const warning = items.filter((item) => item.status === "warning").length;
  const blocked = items.filter((item) => item.status === "blocked").length;
  const nextBlocker = [...items].sort((a, b) => a.score - b.score)[0];

  return {
    averageScore,
    ready,
    warning,
    blocked,
    total: items.length,
    nextBlocker,
  };
}
