export const visualAssets = {
  homeHero: "/images/ai/home-hero-desktop.png",
  homeHeroMobile: "/images/ai/home-hero-mobile.png",
  avesta: "/images/ai/avesta-portal.png",
  gathas: "/images/ai/gathas-hero.png",
  zoroaster: "/images/ai/zoroaster-hero.png",
  zoroastrianism: "/images/ai/zoroastrianism-hero.png",
  monotheism: "/images/ai/monotheism-hero.png",
  dictionary: "/images/ai/dictionary-hero.png",
  articles: "/images/ai/articles-hero.png",
  library: "/images/ai/library-hero.png",
  media: "/images/ai/media-hero.png",
  exhibitions: "/images/ai/exhibitions-hero.png",
  timeline: "/images/ai/timeline-hero.png",
  shop: "/images/ai/shop-hero.png",
  mobed: "/images/ai/mobed-hero.png",
  yasna: "/images/ai/yasna-hero.png",
  vendidad: "/images/ai/vendidad-hero.png",
  yashts: "/images/ai/yashts-hero.png",
  khordehAvesta: "/images/ai/khordeh-avesta-hero.png",
  hats: "/images/ai/hats-cover.png",
  productBook: "/images/ai/product-book.png",
  productMug: "/images/ai/product-mug.png",
  productShirt: "/images/ai/product-shirt.png",
  productStatue: "/images/ai/product-statue.png",
} as const;

export const sectionCoverBySlug: Record<string, string> = {
  yasna: visualAssets.yasna,
  gathas: visualAssets.gathas,
  visperad: visualAssets.avesta,
  vendidad: visualAssets.vendidad,
  yashts: visualAssets.yashts,
  "khordeh-avesta": visualAssets.khordehAvesta,
  hats: visualAssets.hats,
};

export const routeHeroByPath: Record<string, string> = {
  "/": visualAssets.homeHero,
  "/avesta": visualAssets.avesta,
  "/gathas": visualAssets.gathas,
  "/zoroaster": visualAssets.zoroaster,
  "/zoroastrianism": visualAssets.zoroastrianism,
  "/monotheism": visualAssets.monotheism,
  "/dictionary": visualAssets.dictionary,
  "/articles": visualAssets.articles,
  "/library": visualAssets.library,
  "/media": visualAssets.media,
  "/exhibitions": visualAssets.exhibitions,
  "/timeline": visualAssets.timeline,
  "/shop": visualAssets.shop,
  "/mobed": visualAssets.mobed,
};
